### ISSUE TITLE
Change VNet address space to 10.0.0.0/16 to allow for VNet peering in aks.bicep

### ISSUE THREAD

**Issue by srajtiwari** [Azure/azure-orbital-integration#119]
VNet peering requires participating VNets to have non-overlapping address spaces. The current default address space (10.0.0.0/8) does not allow this. 
https://github.com/Azure/azure-orbital-integration/blob/1cd9c6ba4a7615c5cb76af17f4743c08ad6c581c/tcp-to-blob/deploy/bicep/aks.bicep#L32

**Comment by micholas** [comment]
Duplicates #112
