### ISSUE TITLE
User cannot select VM SKU 

### ISSUE THREAD

**Issue by hrshelar** [Azure/azure-orbital-integration#185]
West US 2 and now Southeast Asia have capacity limitations. It would be really powerful to have the user choose a VM SKU or have the pipeline try a few VMs if it runs into shortages.

**Comment by karthick-rn** [comment]
I ran into the quota issue in WU2 earlier this month & had to increase the Total Regional vCPUs quota for the sub.
By default, the aqua processor deploys a `Standard D16ads v5 (16 vcpus, 64 GiB memory)`, and based on my earlier tests, I have faced "Out of memory" errors during IPOPP ingestion when we select anything below the size of this VM SKU. I'm assuming this may be the reason for the dev to prefer this VM SKU as default. I'm happy to look into this further, let me know your thoughts. Thanks

**Comment by hrshelar** [comment]
Got it, thanks for the background! Perhaps just update the readme prerequisites to have the user update their quotas accordingly.
